// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"github.com/ismaelpereira/telegram-bot-isma/bot"
	"github.com/ismaelpereira/telegram-bot-isma/config"
)

// Injectors from app.go:

func Build() (*App, error) {
	configConfig, err := config.Wire()
	if err != nil {
		return nil, err
	}
	botBot, err := bot.Wire(configConfig)
	if err != nil {
		return nil, err
	}
	app, err := Wire(configConfig, botBot)
	if err != nil {
		return nil, err
	}
	return app, nil
}

// app.go:

type App struct {
	Config *config.Config
	Bot    *bot.Bot
}

func Wire(
	cfg *config.Config, bot2 *bot.Bot,
) (*App, error) {
	return &App{
		Config: cfg,
		Bot:    bot2,
	}, nil
}
