// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	redis2 "github.com/go-redis/redis/v7"
	"github.com/ismaelpereira/telegram-bot-isma/bot"
	"github.com/ismaelpereira/telegram-bot-isma/config"
	"github.com/ismaelpereira/telegram-bot-isma/redis"
)

// Injectors from app.go:

func Build() (*App, error) {
	configConfig, err := config.Wire()
	if err != nil {
		return nil, err
	}
	client, err := redis.Wire(configConfig)
	if err != nil {
		return nil, err
	}
	botBot, err := bot.Wire(configConfig, client)
	if err != nil {
		return nil, err
	}
	app, err := Wire(configConfig, client, botBot)
	if err != nil {
		return nil, err
	}
	return app, nil
}

// app.go:

type App struct {
	Config *config.Config
	Redis  *redis2.Client
	Bot    *bot.Bot
}

func Wire(
	cfg *config.Config,
	client *redis2.Client, bot2 *bot.Bot,
) (*App, error) {
	return &App{
		Config: cfg,
		Redis:  client,
		Bot:    bot2,
	}, nil
}
